# DataPrep

This project needs to be at least 10 columns, with attractive visuals in Tableau that help tell a story.

# Library Imports

In [33]:
import pandas as pd
import pylast
import time
from tqdm import tqdm  # For progress bars

In [6]:
# Load datasets
concerts = pd.read_csv("data/ConcertArchivesExportFeb22-25.csv")  # All concerts
twentyfour = pd.read_csv("data/2024concertsranked.csv")  # 2024 concerts with rankings
bestof24 = pd.read_csv("data/bestof24.csv")  # Best albums/songs of 2024
bestof23 = pd.read_csv("data/bestof23.csv")  # Best albums/songs of 2023
bestof22 = pd.read_csv("data/bestof22.csv")  # Best albums/songs of 2022
bestof21 = pd.read_csv("data/bestof21.csv")  # Best albums/songs of 2021
scrobbles = pd.read_csv("data/scrobbles.csv") #Every song I've listened to since May 2020

# View Data

In [8]:
# Display the first few rows of each dataset
twentyfour.head()

,Ranking,Start Date,Concert Name,Bands,Venue,Location,Rating,Paid,Discount
0,1,02/08/2024,NaN,Willi Carlisle / Golden Shoals,Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1,NaN
1,2,01/13/2024,Pool Sounds v3,Lady Bird / Max Niemann / Jacob Slade / Maximi...,Pool Studios,"Milwaukee, Wisconsin, United States",5.0,1,NaN
2,3,03/31/2024,"Barely Civil ""I'd Say I'm Not Fine"" Record Rel...",Barely Civil / Magazine Beach / Overhand / Kno...,Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1,NaN
3,4,04/20/2024,Record Store Day 2024,Friko,Liliput Records,"Milwaukee, Wisconsin, United States",5.0,0,Record Store Day
4,5,08/02/2024,NaN,J.E. Sunde / Caley Conway,Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1,NaN

In [9]:
twentyfour.shape

(57, 9)

In [10]:
concerts.head()

,Start Date,End Date,Concert Name,Bands,Venue,Location
0,02/22/2025,NaN,Riverwest Radio Spotlight Series,Barely Civil / Wave Chapelle / Caley Conway / 2hi,Amorphic Beer,"Milwaukee, Wisconsin, United States"
1,01/29/2025,NaN,the DIVE tour,Almost Monday / Adrian Lyles,Vivarium,"Milwaukee, Wisconsin, United States"
2,01/24/2025,NaN,NaN,Beach Bunny / Delaney Bailey,Turner Hall Ballroom,"Milwaukee, Wisconsin, United States"
3,01/23/2025,NaN,NaN,Orillia / Poor Ridley / Maximiano,Sugar Maple,"Milwaukee, Wisconsin, United States"
4,12/26/2024,NaN,NaN,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States"

In [11]:
concerts.shape

(221, 6)

In [12]:
# Merge concerts and twentyfour
df_concerts = pd.merge(
    concerts,                      # Left dataset
    twentyfour,                    # Right dataset
    on=['Start Date', 'Concert Name', 'Bands', 'Venue', 'Location'],  # Key columns
    how='left'                     # Keep all rows from concerts, add matching rows from twentyfour
)

# Display the merged dataset
df_concerts.head()

,Start Date,End Date,Concert Name,Bands,Venue,Location,Ranking,Rating,Paid,Discount
0,02/22/2025,NaN,Riverwest Radio Spotlight Series,Barely Civil / Wave Chapelle / Caley Conway / 2hi,Amorphic Beer,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
1,01/29/2025,NaN,the DIVE tour,Almost Monday / Adrian Lyles,Vivarium,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
2,01/24/2025,NaN,NaN,Beach Bunny / Delaney Bailey,Turner Hall Ballroom,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
3,01/23/2025,NaN,NaN,Orillia / Poor Ridley / Maximiano,Sugar Maple,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
4,12/26/2024,NaN,NaN,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,NaN

In [13]:
df_concerts.shape

(221, 10)

In [219]:
df_concerts['Location'].value_counts()

Location
Milwaukee, Wisconsin, United States          161
Chicago, Illinois, United States               7
Appleton, Wisconsin, United States             7
Madison, Wisconsin, United States              7
Cudahy, Wisconsin, United States               3
Oshkosh, Wisconsin, United States              3
Minneapolis, Minnesota, United States          3
Sheboygan, Wisconsin, United States            2
Egg Harbor, Wisconsin, United States           2
Green Bay, Wisconsin, United States            1
Egg Harbor, WI, US                             1
Sturgeon Bay, WI                               1
Toronto, Ontario, Canada                       1
Reedsburg, Wisconsin, United States            1
Los Angeles, California, United States         1
1001 Elmwood Ave, Oshkosh, WI 54901            1
2 Jackson St, Oshkosh, WI 54901                1
New York, New York, United States              1
Fort Atkinson, Wisconsin, United States        1
Omaha, Nebraska, United States                 1
West Bend, WI                                  1
Arcadia, MN, United States                     1
Portland, Oregon, United States                1
Seattle, Washington, United States             1
West Allis, Wisconsin, United States           1
Cambridge, Massachusetts, United States        1
Stoughton, Wisconsin, United States            1
Hartland, WI, US                               1
Philadelphia, Pennsylvania, United States      1
Davenport, Iowa, United States                 1
La Crosse, WI, US                              1
La Crosse, Wisconsin, United States            1
Eau Claire, Wisconsin, United States           1
Ferndale, Michigan, United States              1
Bayfield, WI                                   1
Name: count, dtype: int64

In [14]:
# Check for missing values in the merged dataset
print(df_concerts.isnull().sum())

Start Date        0
End Date        216
Concert Name    145
Bands             0
Venue             0
Location          0
Ranking         173
Rating          173
Paid            173
Discount        188
dtype: int64

## Drop Unnessesary Columns

In [16]:
# Drop End Date and Concert Name columns
df_concerts = df_concerts.drop(columns=['End Date', 'Concert Name'])
df_concerts

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount
0,02/22/2025,Barely Civil / Wave Chapelle / Caley Conway / 2hi,Amorphic Beer,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
1,01/29/2025,Almost Monday / Adrian Lyles,Vivarium,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
2,01/24/2025,Beach Bunny / Delaney Bailey,Turner Hall Ballroom,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
3,01/23/2025,Orillia / Poor Ridley / Maximiano,Sugar Maple,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
4,12/26/2024,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,NaN
...,...,...,...,...,...,...,...,...
216,11/18/2011,The Avett Brothers,The Riverside Theater,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
217,07/26/2011,Blitzen Trapper / Ages and Ages,Slowdown,"Omaha, Nebraska, United States",NaN,NaN,NaN,NaN
218,07/11/2010,The Avett Brothers / Elephant Revival,Lake Superior Big Top Chautauqua,"Bayfield, WI",NaN,NaN,NaN,NaN
219,03/06/2010,The Low Anthem / The Avett Brothers,The Riverside Theater,"Milwaukee, Wisconsin, United States",NaN,NaN,NaN,NaN
220,02/19/2010,Diane Schuur,Fox Cities Performing Arts Center,"Appleton, Wisconsin, United States",NaN,NaN,NaN,NaN

## Fill Remaining Nulls

In [18]:
# Fill missing values
df_concerts['Ranking'] = df_concerts['Ranking'].fillna(0)
df_concerts['Rating'] = df_concerts['Rating'].fillna(0)
df_concerts['Paid'] = df_concerts['Paid'].fillna(1)  # Assume missing values mean paid
df_concerts['Discount'] = df_concerts['Discount'].fillna("Unknown")

# Display the updated df
df_concerts.head()

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount
0,02/22/2025,Barely Civil / Wave Chapelle / Caley Conway / 2hi,Amorphic Beer,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown
1,01/29/2025,Almost Monday / Adrian Lyles,Vivarium,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown
2,01/24/2025,Beach Bunny / Delaney Bailey,Turner Hall Ballroom,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown
3,01/23/2025,Orillia / Poor Ridley / Maximiano,Sugar Maple,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown
4,12/26/2024,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown

In [19]:
# Convert Start Date to datetime
df_concerts['Start Date'] = pd.to_datetime(df_concerts['Start Date'], format='%m/%d/%Y')

# Filter for 2024 data
df_2024 = df_concerts[df_concerts['Start Date'].dt.year == 2024]

# Display the filtered dataset
df_2024.head()

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount
4,2024-12-26,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown
5,2024-11-13,Modest Mouse / The Black Heart Procession,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown
6,2024-11-09,Haley Heynderickx / Lily Breshears,Vivarium,"Milwaukee, Wisconsin, United States",7.0,5.0,0.0,Street Team
7,2024-11-02,The Menzingers / Direct Hit! / Holy Pinto,The Rave,"Milwaukee, Wisconsin, United States",15.0,4.5,0.0,Rave Contest
8,2024-10-24,The Nunnery / Dosh / Luke Callen / Maximiano /...,Cactus Club,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown

## Extract a list of unique venues visited in 2024

In [21]:
# Get unique venues
unique_venues = df_2024['Venue'].unique()

# Convert to a DataFrame
df_unique_venues = pd.DataFrame(unique_venues, columns=['Venue'])

# Display the unique venues
df_unique_venues

                                                Venue
0                                         Cactus Club
1                               The Riverside Theater
2                                            Vivarium
3                                            The Rave
4                                   Riverwalk Commons
5                                       Pabst Theater
6                      88Nine Radio Milwaukee Studios
7                                        X-Ray Arcade
8                                The Rave/Eagles Club
9                            Miller High Life Theatre
10  Peck Pavilion, Marcus Center for the Performin...
11                                      Humboldt Park
12                                         Summerfest
13  Summerfest Grounds at Henry Maier Festival Par...
14                          Henry Maier Festival Park
15    Summerfest Grounds at Henry Maier Festival Park
16                                        Thalia Hall
17                               Turner Hall Ballroom
18                                    Liliput Records
19                                    Paradigm Coffee
20                                    Riviera Theatre
21                           Linneman's Riverwest Inn
22              Marcus Center for the Performing Arts
23                      Marcus Performing Arts Center
24                                       Pool Studios

In [22]:
# Save to CSV
df_unique_venues.to_csv("data/unique_venues_2024.csv", index=False)

#### I manually typed the distance from home, time to travel, and venue capacity by hand in Google Sheets

In [24]:
# Load the venue details CSV
venue_info = pd.read_csv("data/venue_info_2024.csv")

# Display the first few rows
venue_info.head()

                   Venue  dist_from_home  drive_time  capacity
0            Cactus Club             9.5          15       150
1  The Riverside Theater             5.5          12      2450
2               Vivarium             5.5          16       450
3               The Rave             4.9          10      1000
4      Riverwalk Commons             6.4          12       100

In [25]:
## Merge Back with df_2024

In [26]:
# Merge the datasets
df_2024 = pd.merge(
    df_2024,                      # Left dataset
    venue_info,                   # Right dataset
    on='Venue',                   # Key column
    how='left'                    # Keep all rows from df_2024
)

# Display the updated dataset
df_2024.head()

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity
0,2024-12-26,Johanna Rose / Ellie Jackson / Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150
1,2024-11-13,Modest Mouse / The Black Heart Procession,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450
2,2024-11-09,Haley Heynderickx / Lily Breshears,Vivarium,"Milwaukee, Wisconsin, United States",7.0,5.0,0.0,Street Team,5.5,16,450
3,2024-11-02,The Menzingers / Direct Hit! / Holy Pinto,The Rave,"Milwaukee, Wisconsin, United States",15.0,4.5,0.0,Rave Contest,4.9,10,1000
4,2024-10-24,The Nunnery / Dosh / Luke Callen / Maximiano /...,Cactus Club,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,9.5,15,150

In [28]:
# Define a mapping dictionary for venue names
venue_name_mapping = {
    'The Rave/Eagles Club': 'The Rave',
    'Marcus Performing Arts Center': 'Marcus Center for the Performing Arts',
    'Summerfest Grounds at Henry Maier Festival Park-M & I Bank Classic Rock Stage': 'Summerfest Grounds at Henry Maier Festival Park',
}

# Standardize venue names in df_2024
df_2024['Venue'] = df_2024['Venue'].replace(venue_name_mapping)

# Standardize venue names in venue_info
venue_info['Venue'] = venue_info['Venue'].replace(venue_name_mapping)

In [29]:
# Add a ranking column to each bestof dataset
bestof24['Rank'] = bestof24.index + 1  # Index starts at 0, so add 1
bestof23['Rank'] = bestof23.index + 1
bestof22['Rank'] = bestof22.index + 1
bestof21['Rank'] = bestof21.index + 1

# Display the updated bestof24 dataset
bestof24.head()

,Track ID,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Added By,Added At,Genres,...,Loudness,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Rank
0,24TyIHRNtcNihfFoWKkqzP,Where We've Been,"Where we've been, Where we go from here",Friko,2024-02-16,315633,32,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:12:53Z,NaN,...,-10.981,1,0.0437,0.7870,0.041200,0.0876,0.116,146.426,4,1
1,78SjYKRXdivtTDHBzaehnm,The Architect,Deeper Well,Kacey Musgraves,2024-03-15,177293,55,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:13:50Z,NaN,...,-8.603,1,0.0320,0.8420,0.000000,0.0858,0.441,123.285,4,2
2,42gvftYbB8lU8B6pP7Hp6k,Jaybird,Critterland,Willi Carlisle,2024-01-26,233091,22,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:05Z,"alt country,americana,bluegrass",...,-10.130,1,0.0303,0.6470,0.000044,0.1560,0.527,122.981,4,3
3,0nj9Bq5sHDiTxSHunhgkFb,squabble up,GNX,Kendrick Lamar,2024-11-22,157992,88,mmr4r23xnc6oh1c77lysfbqg4,2024-12-03T14:02:59Z,"hip hop,west coast hip hop",...,-5.568,1,0.1980,0.0206,0.000000,0.0783,0.711,103.921,4,4
4,1Ov33kwQ8c0ZnKIiHo7yl6,Summer Bodies,No Souvenirs,Fightmilk,2024-11-15,228506,5,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:40Z,NaN,...,-5.166,1,0.0563,0.0182,0.000015,0.1300,0.395,127.861,4,5

In [30]:
# Add a year column to each dataset
bestof24['Year'] = 2024
bestof23['Year'] = 2023
bestof22['Year'] = 2022
bestof21['Year'] = 2021

# Combine all bestof datasets
bestof_all = pd.concat([bestof24, bestof23, bestof22, bestof21], ignore_index=True)

# Display the combined dataset
bestof_all.head()

,Track ID,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Added By,Added At,Genres,...,Mode,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Rank,Year
0,24TyIHRNtcNihfFoWKkqzP,Where We've Been,"Where we've been, Where we go from here",Friko,2024-02-16,315633,32,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:12:53Z,NaN,...,1,0.0437,0.7870,0.041200,0.0876,0.116,146.426,4,1,2024
1,78SjYKRXdivtTDHBzaehnm,The Architect,Deeper Well,Kacey Musgraves,2024-03-15,177293,55,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:13:50Z,NaN,...,1,0.0320,0.8420,0.000000,0.0858,0.441,123.285,4,2,2024
2,42gvftYbB8lU8B6pP7Hp6k,Jaybird,Critterland,Willi Carlisle,2024-01-26,233091,22,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:05Z,"alt country,americana,bluegrass",...,1,0.0303,0.6470,0.000044,0.1560,0.527,122.981,4,3,2024
3,0nj9Bq5sHDiTxSHunhgkFb,squabble up,GNX,Kendrick Lamar,2024-11-22,157992,88,mmr4r23xnc6oh1c77lysfbqg4,2024-12-03T14:02:59Z,"hip hop,west coast hip hop",...,1,0.1980,0.0206,0.000000,0.0783,0.711,103.921,4,4,2024
4,1Ov33kwQ8c0ZnKIiHo7yl6,Summer Bodies,No Souvenirs,Fightmilk,2024-11-15,228506,5,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:40Z,NaN,...,1,0.0563,0.0182,0.000015,0.1300,0.395,127.861,4,5,2024

In [31]:
# Define a function to categorize albums
def categorize_album(rank):
    if rank <= 5:
        return 'Top 5'
    elif rank <= 10:
        return 'Top 10'
    elif rank <= 25:
        return 'Top 25'
    elif rank <= 50:
        return 'Top 50'
    elif rank <= 100:
        return 'Top 100'
    else:
        return 'Not in Top 100'

# Apply the function to create a new column
bestof_all['Tier'] = bestof_all['Rank'].apply(categorize_album)

# Display the updated dataset
bestof_all.head()

,Track ID,Track Name,Album Name,Artist Name(s),Release Date,Duration (ms),Popularity,Added By,Added At,Genres,...,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Time Signature,Rank,Year,Tier
0,24TyIHRNtcNihfFoWKkqzP,Where We've Been,"Where we've been, Where we go from here",Friko,2024-02-16,315633,32,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:12:53Z,NaN,...,0.0437,0.7870,0.041200,0.0876,0.116,146.426,4,1,2024,Top 5
1,78SjYKRXdivtTDHBzaehnm,The Architect,Deeper Well,Kacey Musgraves,2024-03-15,177293,55,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:13:50Z,NaN,...,0.0320,0.8420,0.000000,0.0858,0.441,123.285,4,2,2024,Top 5
2,42gvftYbB8lU8B6pP7Hp6k,Jaybird,Critterland,Willi Carlisle,2024-01-26,233091,22,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:05Z,"alt country,americana,bluegrass",...,0.0303,0.6470,0.000044,0.1560,0.527,122.981,4,3,2024,Top 5
3,0nj9Bq5sHDiTxSHunhgkFb,squabble up,GNX,Kendrick Lamar,2024-11-22,157992,88,mmr4r23xnc6oh1c77lysfbqg4,2024-12-03T14:02:59Z,"hip hop,west coast hip hop",...,0.1980,0.0206,0.000000,0.0783,0.711,103.921,4,4,2024,Top 5
4,1Ov33kwQ8c0ZnKIiHo7yl6,Summer Bodies,No Souvenirs,Fightmilk,2024-11-15,228506,5,mmr4r23xnc6oh1c77lysfbqg4,2024-12-02T20:14:40Z,NaN,...,0.0563,0.0182,0.000015,0.1300,0.395,127.861,4,5,2024,Top 5

In [32]:
bestof_all.columns

Index(['Track ID', 'Track Name', 'Album Name', 'Artist Name(s)',
       'Release Date', 'Duration (ms)', 'Popularity', 'Added By', 'Added At',
       'Genres', 'Record Label', 'Danceability', 'Energy', 'Key', 'Loudness',
       'Mode', 'Speechiness', 'Acousticness', 'Instrumentalness', 'Liveness',
       'Valence', 'Tempo', 'Time Signature', 'Rank', 'Year', 'Tier'],
      dtype='object')

## Drop Unnessisary Columns

In [34]:
# Drop unnecessary columns
bestof_all = bestof_all[['Artist Name(s)', 'Album Name', 'Release Date', 'Rank', 'Year', 'Tier']]

# Display the updated dataset
bestof_all.head()

,Artist Name(s),Album Name,Release Date,Rank,Year,Tier
0,Friko,"Where we've been, Where we go from here",2024-02-16,1,2024,Top 5
1,Kacey Musgraves,Deeper Well,2024-03-15,2,2024,Top 5
2,Willi Carlisle,Critterland,2024-01-26,3,2024,Top 5
3,Kendrick Lamar,GNX,2024-11-22,4,2024,Top 5
4,Fightmilk,No Souvenirs,2024-11-15,5,2024,Top 5

In [104]:
# Define a function to extract the primary artist name
def extract_primary_artist(artist_name):
    if pd.isna(artist_name):
        return None
    # Handle special case for "Tyler, The Creator"
    if "Tyler, The Creator" in artist_name:
        return "Tyler, The Creator"
    # Split on comma and return the first artist
    return artist_name.split(',')[0].strip()

# Apply the function to create a new column
bestof_all['Primary Artist'] = bestof_all['Artist Name(s)'].apply(extract_primary_artist)

# Display the updated dataset
bestof_all.head()

,Artist Name(s),Album Name,Release Date,Rank,Year,Tier,Primary Artist
0,Friko,"Where we've been, Where we go from here",2024-02-16,1,2024,Top 5,Friko
1,Kacey Musgraves,Deeper Well,2024-03-15,2,2024,Top 5,Kacey Musgraves
2,Willi Carlisle,Critterland,2024-01-26,3,2024,Top 5,Willi Carlisle
3,Kendrick Lamar,GNX,2024-11-22,4,2024,Top 5,Kendrick Lamar
4,Fightmilk,No Souvenirs,2024-11-15,5,2024,Top 5,Fightmilk

In [108]:
bestof_all.columns

Index(['Artist Name(s)', 'Album Name', 'Release Date', 'Rank', 'Year', 'Tier',
       'Primary Artist'],
      dtype='object')

## Attempt to Merge bestof_all and df_2024

In [37]:
# Split the Bands column into multiple rows
df_exploded = df_2024.assign(Bands=df_2024['Bands'].str.split(' / ')).explode('Bands')

# Display the exploded dataset
df_exploded.head()

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity
0,2024-12-26,Johanna Rose,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150
0,2024-12-26,Ellie Jackson,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150
0,2024-12-26,Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150
1,2024-11-13,Modest Mouse,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450
1,2024-11-13,The Black Heart Procession,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450

In [92]:
df_exploded.columns

Index(['Start Date', 'Bands', 'Venue', 'Location', 'Ranking', 'Rating', 'Paid',
       'Discount', 'dist_from_home', 'drive_time', 'capacity'],
      dtype='object')

In [96]:
from thefuzz import process
import re

# Ensure dates are datetime objects
scrobbles['Timestamp'] = pd.to_datetime(scrobbles['Timestamp'])
df_exploded['Start Date'] = pd.to_datetime(df_exploded['Start Date'])

# Function to clean artist names (removes featured artists, punctuation, etc.)
def clean_artist_name(artist):
    # Remove content in parentheses and after "feat." or "ft."
    artist = re.sub(r'\s*\(.*?\)|\s*feat\..*|ft\..*', '', artist, flags=re.IGNORECASE)
    return artist.strip()

# Clean scrobble artist names
scrobbles['Cleaned Artist'] = scrobbles['Artist'].apply(clean_artist_name)

# Fuzzy matching function to get closest artist match
def get_closest_artist(artist, artist_list, threshold=80):
    match, score = process.extractOne(artist, artist_list)
    return match if score >= threshold else None

# Count scrobbles for each artist before the concert date
def count_scrobbles_before_concert(row):
    concert_date = row['Start Date']
    concert_artist = row['Bands']
    
    # Get closest match for concert artist from cleaned artist list
    matched_artist = get_closest_artist(concert_artist, scrobbles['Cleaned Artist'].unique())
    
    if matched_artist:
        count = scrobbles[(scrobbles['Cleaned Artist'] == matched_artist) & 
                          (scrobbles['Timestamp'] < concert_date)].shape[0]
    else:
        count = 0
    
    return count

# Add the scrobble count to df_exploded
df_exploded['Scrobbles Before Concert'] = df_exploded.apply(count_scrobbles_before_concert, axis=1)

# Preview the updated dataframe
print(df_exploded[['Bands', 'Start Date', 'Scrobbles Before Concert']].head())

                        Bands Start Date  Scrobbles Before Concert
0                Johanna Rose 2024-12-26                         0
0               Ellie Jackson 2024-12-26                         7
0                 Bitch Creek 2024-12-26                         9
1                Modest Mouse 2024-11-13                        88
1  The Black Heart Procession 2024-11-13                         1

In [102]:
df_exploded.head()

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity,Scrobbles Before Concert
0,2024-12-26,Johanna Rose,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,0
0,2024-12-26,Ellie Jackson,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,7
0,2024-12-26,Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,9
1,2024-11-13,Modest Mouse,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450,88
1,2024-11-13,The Black Heart Procession,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450,1

In [106]:
df_exploded.columns

Index(['Start Date', 'Bands', 'Venue', 'Location', 'Ranking', 'Rating', 'Paid',
       'Discount', 'dist_from_home', 'drive_time', 'capacity',
       'Scrobbles Before Concert'],
      dtype='object')

In [126]:
import pandas as pd
from datetime import datetime

# Convert release date in bestof_all to datetime
bestof_all['Release Date'] = pd.to_datetime(bestof_all['Release Date'])

# Merge the data on the artist and primary artist
merged_df = pd.merge(df_exploded, bestof_all, left_on='Bands', right_on='Primary Artist', how='left')

# Ensure 'Release Date' is not NaN before applying idxmax
most_recent_album = merged_df.dropna(subset=['Release Date']).groupby('Bands').apply(
    lambda x: x.loc[x['Release Date'].idxmax()] if not x['Release Date'].isnull().all() else pd.Series())
most_recent_album = most_recent_album[['Bands', 'Album Name', 'Release Date', 'Tier']]

# Reset index to avoid ambiguity in merge
merged_df = merged_df.reset_index(drop=True)
most_recent_album = most_recent_album.reset_index(drop=True)

# Merge this back into the original exploded dataframe
merged_df = pd.merge(df_exploded, most_recent_album, left_on='Bands', right_on='Bands', how='left')

# Calculate wait time for each concert
def calculate_wait_time(row):
    if pd.isna(row['Release Date']):
        return 'N/A'
    concert_date = pd.to_datetime(row['Start Date'])
    release_date = row['Release Date']
    delta = concert_date - release_date
    years = delta.days // 365
    months = (delta.days % 365) // 30
    days = (delta.days % 365) % 30
    if years == 0 and months == 0 and days == 0:
        return f"{years} years, {months} months, {days} days"
    return f"{years} years, {months} months, {days} days"

# Apply the wait time calculation
merged_df['Wait Time'] = merged_df.apply(calculate_wait_time, axis=1)

# Format the album and tier
merged_df['Album Info'] = merged_df.apply(
    lambda row: f"{row['Tier']} ({row['Release Date'].year}) - {row['Album Name']}" if pd.notna(row['Album Name']) else "N/A", 
    axis=1)

# Merge df_exploded with bestof_all
merged_df = pd.merge(df_exploded, bestof_all, left_on='Bands', right_on='Primary Artist', how='left')

# Drop rows with NaN in the 'Release Date' column
merged_df_cleaned = merged_df.dropna(subset=['Release Date'])

# Ensure 'Release Date' is not NaN before applying idxmax
most_recent_album = merged_df_cleaned.dropna(subset=['Release Date']).groupby('Bands').apply(
    lambda x: x.loc[x['Release Date'].idxmax()] if not x['Release Date'].isnull().all() else pd.Series())
most_recent_album = most_recent_album[['Bands', 'Album Name', 'Release Date', 'Tier']]

# Reset index again to avoid ambiguity in merge
merged_df_cleaned = merged_df_cleaned.reset_index(drop=True)
most_recent_album = most_recent_album.reset_index(drop=True)

# Merge this back into the original exploded dataframe
merged_df = pd.merge(df_exploded, most_recent_album, left_on='Bands', right_on='Bands', how='left')

# Display the final dataset
merged_df

,Start Date,Bands,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity,Scrobbles Before Concert,Album Name,Release Date,Tier
0,2024-12-26,Johanna Rose,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,0,NaN,NaT,NaN
1,2024-12-26,Ellie Jackson,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,7,NaN,NaT,NaN
2,2024-12-26,Bitch Creek,Cactus Club,"Milwaukee, Wisconsin, United States",26.0,4.5,1.0,Unknown,9.5,15,150,9,NaN,NaT,NaN
3,2024-11-13,Modest Mouse,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450,88,NaN,NaT,NaN
4,2024-11-13,The Black Heart Procession,The Riverside Theater,"Milwaukee, Wisconsin, United States",0.0,0.0,1.0,Unknown,5.5,12,2450,1,NaN,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,2024-01-13,Lady Bird,Pool Studios,"Milwaukee, Wisconsin, United States",2.0,5.0,1.0,Unknown,5.1,12,250,0,NaN,NaT,NaN
154,2024-01-13,Max Niemann,Pool Studios,"Milwaukee, Wisconsin, United States",2.0,5.0,1.0,Unknown,5.1,12,250,23,NaN,NaT,NaN
155,2024-01-13,Jacob Slade,Pool Studios,"Milwaukee, Wisconsin, United States",2.0,5.0,1.0,Unknown,5.1,12,250,92,Soft Spoken,2023-10-13,Top 25
156,2024-01-13,Maximiano,Pool Studios,"Milwaukee, Wisconsin, United States",2.0,5.0,1.0,Unknown,5.1,12,250,0,The Real Truth,2024-09-07,Top 25
157,2024-01-13,Jack Eyke,Pool Studios,"Milwaukee, Wisconsin, United States",2.0,5.0,1.0,Unknown,5.1,12,250,5,NaN,NaT,NaN

In [154]:
merged_df.columns

Index(['Start Date', 'Bands', 'Venue', 'Location', 'Ranking', 'Rating', 'Paid',
       'Discount', 'dist_from_home', 'drive_time', 'capacity',
       'Scrobbles Before Concert', 'Album Name', 'Release Date', 'Tier',
       'Is Local'],
      dtype='object')

In [165]:
merged_df.to_excel('data/cleaned24.xlsx', index=False)

## Added some features in Google Sheets, namely, identifying which artists were local, and which artists from summerfest i never saw!

In [171]:
# Load the Excel file into a DataFrame
final_data = pd.read_excel('data/cleaned24withlocalindicator.xlsx')

# View the first few rows to ensure it's loaded correctly
final_data.head()

,Start Date,Bands,Is Local,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity,Scrobbles Before Concert,Album Name,Release Date,Tier
0,2024-01-13,Lady Bird,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,0,NaN,NaT,NaN
1,2024-01-13,Max Niemann,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,23,NaN,NaT,NaN
2,2024-01-13,Jacob Slade,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,92,Soft Spoken,2023-10-13,Top 25
3,2024-01-13,Maximiano,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,0,The Real Truth,2024-09-07,Top 25
4,2024-01-13,Jack Eyke,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,5,NaN,NaT,NaN

In [173]:
final_data.columns

Index(['Start Date', 'Bands', 'Is Local', 'Venue', 'Location', 'Ranking',
       'Rating', 'Paid', 'Discount', 'dist_from_home', 'drive_time',
       'capacity', 'Scrobbles Before Concert', 'Album Name', 'Release Date',
       'Tier'],
      dtype='object')

In [181]:
# Ensure date columns are in datetime format
final_data['Start Date'] = pd.to_datetime(final_data['Start Date'], errors='coerce')
final_data['Release Date'] = pd.to_datetime(final_data['Release Date'], errors='coerce')

# Calculate the 'Waited' column
final_data['Waited'] = final_data.apply(
    lambda row: f"{(row['Start Date'] - row['Release Date']).days} day(s)" 
    if pd.notnull(row['Release Date']) and row['Start Date'] >= row['Release Date'] else '',
    axis=1
)

# Save the updated DataFrame to a new Excel file
final_data.to_excel('final_data_with_waited_column.xlsx', index=False)

# Check the output
final_data[['Bands', 'Start Date', 'Release Date', 'Waited']]

                          Bands Start Date Release Date     Waited
0                     Lady Bird 2024-01-13          NaT
1                   Max Niemann 2024-01-13          NaT
2                   Jacob Slade 2024-01-13   2023-10-13  92 day(s)
3                     Maximiano 2024-01-13   2024-09-07
4                     Jack Eyke 2024-01-13          NaT
..                          ...        ...          ...        ...
117                Modest Mouse 2024-11-13          NaT
118  The Black Heart Procession 2024-11-13          NaT
119                Johanna Rose 2024-12-26          NaT
120               Ellie Jackson 2024-12-26          NaT
121                 Bitch Creek 2024-12-26          NaT

[122 rows x 4 columns]

In [183]:
final_data

,Start Date,Bands,Is Local,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity,Scrobbles Before Concert,Album Name,Release Date,Tier,Waited
0,2024-01-13,Lady Bird,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,0,NaN,NaT,NaN,
1,2024-01-13,Max Niemann,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,23,NaN,NaT,NaN,
2,2024-01-13,Jacob Slade,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,92,Soft Spoken,2023-10-13,Top 25,92 day(s)
3,2024-01-13,Maximiano,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,0,The Real Truth,2024-09-07,Top 25,
4,2024-01-13,Jack Eyke,1.0,Pool Studios,"Milwaukee, Wisconsin, United States",2,5.0,1,Unknown,5.1,12,250,5,NaN,NaT,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,2024-11-13,Modest Mouse,0.0,The Riverside Theater,"Milwaukee, Wisconsin, United States",0,0.0,1,Unknown,5.5,12,2450,88,NaN,NaT,NaN,
118,2024-11-13,The Black Heart Procession,0.0,The Riverside Theater,"Milwaukee, Wisconsin, United States",0,0.0,1,Unknown,5.5,12,2450,1,NaN,NaT,NaN,
119,2024-12-26,Johanna Rose,0.0,Cactus Club,"Milwaukee, Wisconsin, United States",26,4.5,1,Unknown,9.5,15,150,0,NaN,NaT,NaN,
120,2024-12-26,Ellie Jackson,1.0,Cactus Club,"Milwaukee, Wisconsin, United States",26,4.5,1,Unknown,9.5,15,150,7,NaN,NaT,NaN,
121,2024-12-26,Bitch Creek,1.0,Cactus Club,"Milwaukee, Wisconsin, United States",26,4.5,1,Unknown,9.5,15,150,9,NaN,NaT,NaN,

In [187]:
final_data.dtypes

Start Date                  datetime64[ns]
Bands                               object
Is Local                           float64
Venue                               object
Location                            object
Ranking                              int64
Rating                             float64
Paid                                 int64
Discount                            object
dist_from_home                     float64
drive_time                           int64
capacity                             int64
Scrobbles Before Concert             int64
Album Name                          object
Release Date                datetime64[ns]
Tier                                object
Waited                              object
dtype: object

In [191]:
from geopy.geocoders import Nominatim
import pandas as pd

# Initialize the geolocator
geolocator = Nominatim(user_agent="concert_geocoder")

# Function to get the full address from the location
def get_address(location):
    try:
        # Geocode the location
        location_info = geolocator.geocode(location, timeout=10)
        if location_info:
            return location_info.address  # Full address
        else:
            return None
    except Exception as e:
        print(f"Error geocoding {location}: {e}")
        return None

# Create a 'Venue Location' column to identify unique venue-location pairs
final_data['Venue Location'] = final_data['Venue'] + ', ' + final_data['Location']

# Identify unique venue-location pairs
unique_locations = final_data['Venue Location'].drop_duplicates()

# Geocode unique locations
location_addresses = unique_locations.apply(get_address)

# Create a mapping from 'Venue Location' to 'Full Address'
location_to_address = dict(zip(unique_locations, location_addresses))

# Map the 'Full Address' back to the original dataset
final_data['Full Address'] = final_data['Venue Location'].map(location_to_address)

In [199]:
# Filter rows where 'Full Address' is NaN
venues_without_address = final_data[final_data['Full Address'].isna()]

# Display the venues without addresses
venues_without_address[['Venue', 'Location']]

,Venue,Location
0,Pool Studios,"Milwaukee, Wisconsin, United States"
1,Pool Studios,"Milwaukee, Wisconsin, United States"
2,Pool Studios,"Milwaukee, Wisconsin, United States"
3,Pool Studios,"Milwaukee, Wisconsin, United States"
4,Pool Studios,"Milwaukee, Wisconsin, United States"
25,Linneman's Riverwest Inn,"Milwaukee, Wisconsin, United States"
26,Linneman's Riverwest Inn,"Milwaukee, Wisconsin, United States"
27,Linneman's Riverwest Inn,"Milwaukee, Wisconsin, United States"
40,Paradigm Coffee,"Sheboygan, Wisconsin, United States"
45,Liliput Records,"Milwaukee, Wisconsin, United States"
63,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
64,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
67,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
68,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
69,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
70,Summerfest Grounds at Henry Maier Festival Park,"Milwaukee, Wisconsin, United States"
84,"Peck Pavilion, Marcus Center for the Performin...","Milwaukee, Wisconsin, United States"
106,Riverwalk Commons,"Milwaukee, Wisconsin, United States"

In [201]:
# Dictionary mapping venues to their addresses
venue_addresses = {
    'Pool Studios': '3728 N Fratney St, Milwaukee, WI 53212',
    'Linneman\'s Riverwest Inn': '1001 E Locust St, Milwaukee, WI 53212',
    'Paradigm Coffee and Music': '1202 N 8th St, Sheboygan, WI 53081',
    'Lilliput Records': '1669 N Farwell Ave, Milwaukee, WI 53202',
    'Summerfest Grounds at Henry Maier Festival Park': '200 N Harbor Dr, Milwaukee, WI 53202',
    'Peck Pavilion, Marcus Center for the Performing Arts': '929 N Water St, Milwaukee, WI 53202'
}

# Update the 'Full Address' column based on the 'Venue' column
final_data['Full Address'] = final_data['Venue'].replace(venue_addresses)

In [205]:
final_data.isna().sum()

Start Date                   0
Bands                        0
Is Local                     1
Venue                        0
Location                     0
Ranking                      0
Rating                       0
Paid                         0
Discount                     0
dist_from_home               0
drive_time                   0
capacity                     0
Scrobbles Before Concert     0
Album Name                  83
Release Date                83
Tier                        83
Waited                       0
Venue Location               0
Full Address                 0
dtype: int64

In [207]:
final_data[final_data['Is Local'].isna()]

,Start Date,Bands,Is Local,Venue,Location,Ranking,Rating,Paid,Discount,dist_from_home,drive_time,capacity,Scrobbles Before Concert,Album Name,Release Date,Tier,Waited,Venue Location,Full Address
36,2024-03-31,Magazine Beach,NaN,Cactus Club,"Milwaukee, Wisconsin, United States",3,5.0,1,Unknown,9.5,15,150,32,Constant Springtime,2023-04-21,Top 25,345 day(s),"Cactus Club, Milwaukee, Wisconsin, United States",Cactus Club

In [213]:
# Update the 'Is Local' value for the specific concert
final_data.at[36, 'Is Local'] = 0  # 0 indicates the artist is not local

In [217]:
final_data.isna().sum()

Start Date                   0
Bands                        0
Is Local                     0
Venue                        0
Location                     0
Ranking                      0
Rating                       0
Paid                         0
Discount                     0
dist_from_home               0
drive_time                   0
capacity                     0
Scrobbles Before Concert     0
Album Name                  83
Release Date                83
Tier                        83
Waited                       0
Venue Location               0
Full Address                 0
dtype: int64

In [226]:
final_data.to_csv('data/final_data.csv', index=False)

In [56]:
import pandas as pd

# Load your data
df = pd.read_csv('final_data.csv')

# Group by unique concert identifier (Start Date + Venue)
aggregated_data = df.groupby(['Start Date', 'Venue', 'Location', 'capacity']).agg({
    'Bands': lambda x: ', '.join(x),  # Combine bands into a single string
    'Is Local': 'max',                # 1 if any band is local
    'Ranking': 'min',                 # Best ranking
    'Rating': 'max',                  # Highest rating
    'Paid': 'max',                    # 1 if any ticket was paid
    'Discount': 'first',              # First discount reason
    'dist_from_home': 'first',        # First distance
    'drive_time': 'first',            # First drive time
    'Scrobbles Before Concert': 'sum',  # Sum scrobbles across all bands
    'Album Name': 'first',            # First album name
    'Release Date': 'first',          # First release date
    'Tier': 'first',                  # First tier
    'Waited': 'first',                # First wait time
    'Venue Location': 'first',        # First venue location
    'Full Address': 'first',          # First full address
    'Latitude': 'first',              # First latitude
    'Longitude': 'first'              # First longitude
}).reset_index()

# Save the aggregated data to a new CSV
aggregated_data.to_csv('final_data_aggregated.csv', index=False)

In [37]:
aggregated_data.columns

Index(['Start Date', 'Venue', 'Location', 'capacity', 'Bands', 'Is Local',
       'Ranking', 'Rating', 'Paid', 'Discount', 'dist_from_home', 'drive_time',
       'Scrobbles Before Concert', 'Album Name', 'Release Date', 'Tier',
       'Waited', 'Venue Location', 'Full Address', 'Latitude', 'Longitude'],
      dtype='object')

In [43]:
import pandas as pd

# Load the already aggregated data
aggregated_data = pd.read_csv('final_data_aggregated.csv')

# Load the original dataset
df = pd.read_csv('final_data.csv')

# Keep the Marcus Center venues separate (no renaming)
df['Bands'] = df['Bands'].str.split(', ')

# Aggregate bands per concert (Start Date + Venue)
venue_bands = df.groupby(['Start Date', 'Venue'])['Bands'].sum().reset_index()

# Convert bands list back to a string
venue_bands['Bands'] = venue_bands['Bands'].apply(', '.join)

# Merge with the aggregated dataset
merged_data = aggregated_data.merge(venue_bands, on=['Start Date', 'Venue'], how='left')

# Save to CSV for Tableau
merged_data.to_csv('bandsatvenues.csv', index=False)

In [47]:
import pandas as pd

# Load the bands data
bands_data = pd.read_csv('bandsatvenues.csv')

# Aggregate bands by Venue (one list per venue)
venue_bands = bands_data.groupby('Venue')['Bands'].apply(', '.join).reset_index()

# Rename the column to 'Venue_Bands_Complete' for clarity
venue_bands.rename(columns={'Bands': 'Venue_Bands_Complete'}, inplace=True)

# Save only the Venue and the aggregated Bands data
venue_bands.to_csv('venue_bands_for_tableau.csv', index=False)

print("Successfully aggregated venue bands. Now use 'venue_bands_for_tableau.csv' in Tableau!")

KeyError: 'Column not found: Band'

In [49]:
import pandas as pd

# Load the bands data
bands_data = pd.read_csv('bandsatvenues.csv')

# Check the column names
print(bands_data.columns)

Index(['Start Date', 'Venue', 'Location', 'capacity', 'Bands_x', 'Is Local',
       'Ranking', 'Rating', 'Paid', 'Discount', 'dist_from_home', 'drive_time',
       'Scrobbles Before Concert', 'Album Name', 'Release Date', 'Tier',
       'Waited', 'Venue Location', 'Full Address', 'Latitude', 'Longitude',
       'Bands_y'],
      dtype='object')

In [51]:
import pandas as pd

# Load the bands data
bands_data = pd.read_csv('bandsatvenues.csv')

# Check which 'Bands' column contains the actual band names
# We'll assume 'Bands_x' is the one with the relevant data based on the names, but double-check first
bands_data['Bands'] = bands_data['Bands_x'].fillna(bands_data['Bands_y'])

# Aggregate bands by Venue (one list per venue)
venue_bands = bands_data.groupby('Venue')['Bands'].apply(', '.join).reset_index()

# Rename the column to 'Venue_Bands_Complete' for clarity
venue_bands.rename(columns={'Bands': 'Venue_Bands_Complete'}, inplace=True)

# Save the result for Tableau
venue_bands.to_csv('venue_bands_for_tableau.csv', index=False)

print("Successfully aggregated venue bands. Now use 'venue_bands_for_tableau.csv' in Tableau!")

Successfully aggregated venue bands. Now use 'venue_bands_for_tableau.csv' in Tableau!

In [54]:
# Count all rows where Paid = 0
free_concert_count = (aggregated_data['Paid'] == 0).sum()
print(f"Total free concerts (Paid = 0): {free_concert_count}")

# If you need to count unique concerts where Paid = 0
# Assuming 'Concert Group' is your concert identifier column
unique_free_concerts = aggregated_data[aggregated_data['Paid'] == 0]['Concert Group'].nunique()
print(f"Unique free concerts: {unique_free_concerts}")

# To see the distribution of discount reasons for free concerts
if 'Discount' in aggregated_data.columns:
    discount_distribution = aggregated_data[aggregated_data['Paid'] == 0]['Discount'].value_counts()
    print("\nDiscount reasons for free concerts:")
    print(discount_distribution)

Total free concerts (Paid = 0): 33

KeyError: 'Concert Group'

In [81]:
import pandas as pd

# Load your two main datasets
aggregated_data = pd.read_csv('final_data_aggregated.csv')
concerts_ranked = pd.read_csv('data/2024concertsranked.csv')  # Your source of truth for key fields

# Ensure Start Date is in the same format across datasets
aggregated_data['Start Date'] = pd.to_datetime(aggregated_data['Start Date'])
concerts_ranked['Start Date'] = pd.to_datetime(concerts_ranked['Start Date'])

# Apply the same venue name standardization to concerts_ranked that you applied to aggregated_data
venue_name_mapping = {
    'The Rave/Eagles Club': 'The Rave',
    'Marcus Performing Arts Center': 'Marcus Center for the Performing Arts',
    'Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park-M & I Bank Classic Rock Stage': 'Summerfest'
}

# Standardize venue names in concerts_ranked
concerts_ranked['Venue'] = concerts_ranked['Venue'].replace(venue_name_mapping)

# From concerts_ranked, we want the "source of truth" fields
concerts_truth = concerts_ranked[['Start Date', 'Ranking', 'Bands', 'Venue', 'Location', 'Rating', 'Paid', 'Discount']]

# From aggregated_data, we want everything except those fields that are better in concerts_ranked
columns_to_exclude = ['Ranking', 'Bands', 'Location', 'Rating', 'Paid', 'Discount']
aggregated_features = aggregated_data.drop(columns=[col for col in columns_to_exclude if col in aggregated_data.columns])

# First, check for concerts that might not match directly by venue name
print("Unique venues in concerts_ranked:", sorted(concerts_ranked['Venue'].unique()))
print("Unique venues in aggregated_data:", sorted(aggregated_data['Venue'].unique()))

# Now merge on Date and standardized Venue
combined_data = pd.merge(
    concerts_truth,
    aggregated_features,
    on=['Start Date', 'Venue'],
    how='left'
)

# Check for any rows that didn't get the aggregated data
missing_data = combined_data[combined_data['capacity'].isna()]
if not missing_data.empty:
    print(f"Warning: {len(missing_data)} concerts didn't match with aggregated data:")
    print(missing_data[['Start Date', 'Venue', 'Bands']])

# Save the combined dataset
combined_data.to_csv('combined_concert_data_final.csv', index=False)

# Preview the result
print(f"Combined data has {combined_data.shape[0]} rows and {combined_data.shape[1]} columns")
print("First few rows:")
print(combined_data.head())

Unique venues in concerts_ranked: ['88Nine Radio Milwaukee Studios', 'Cactus Club', 'Humboldt Park', 'Liliput Records', "Linneman's Riverwest Inn", 'Marcus Center for the Performing Arts', 'Miller High Life Theatre', 'Pabst Theater', 'Paradigm Coffee', 'Peck Pavilion, Marcus Center for the Performing Arts', 'Pool Studios', 'Riverwalk Commons', 'Riviera Theatre', 'Summerfest', 'Thalia Hall', 'The Rave', 'The Riverside Theater', 'Turner Hall Ballroom', 'Vivarium', 'X-Ray Arcade']
Unique venues in aggregated_data: ['88Nine Radio Milwaukee Studios', 'Cactus Club', 'Humboldt Park', 'Liliput Records', "Linneman's Riverwest Inn", 'Marcus Center for the Performing Arts', 'Miller High Life Theatre', 'Pabst Theater', 'Paradigm Coffee', 'Peck Pavilion, Marcus Center for the Performing Arts', 'Pool Studios', 'Riverwalk Commons', 'Riviera Theatre', 'Summerfest', 'Thalia Hall', 'The Rave', 'The Riverside Theater', 'Turner Hall Ballroom', 'Vivarium', 'X-Ray Arcade']
Combined data has 57 rows and 21 columns
First few rows:
  Start Date  Ranking                                              Bands  \
0 2024-02-08        1                     Willi Carlisle / Golden Shoals
1 2024-01-13        2  Lady Bird / Max Niemann / Jacob Slade / Maximi...
2 2024-03-31        3  Barely Civil / Magazine Beach / Overhand / Kno...
3 2024-04-20        4                                              Friko
4 2024-08-02        5                          J.E. Sunde / Caley Conway

             Venue                             Location  Rating  Paid  \
0      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1
1     Pool Studios  Milwaukee, Wisconsin, United States     5.0     1
2      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1
3  Liliput Records  Milwaukee, Wisconsin, United States     5.0     0
4      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1

           Discount  capacity  Is Local  ...  drive_time  \
0               NaN       150         0  ...          15
1               NaN       250         1  ...          12
2               NaN       150         1  ...          15
3  Record Store Day       120         0  ...          16
4               NaN       150         1  ...          15

   Scrobbles Before Concert                               Album Name  \
0                        53                              Critterland
1                       120                              Soft Spoken
2                        78                     I'd Say I'm Not Fine
3                        43  Where we've been, Where we go from here
4                        86                                      NaN

  Release Date    Tier     Waited  \
0   2024-01-26   Top 5  13 day(s)
1   2023-10-13  Top 25  92 day(s)
2   2024-03-22  Top 10   9 day(s)
3   2024-02-16   Top 5  64 day(s)
4          NaN     NaN        NaN

                                      Venue Location  \
0   Cactus Club, Milwaukee, Wisconsin, United States
1  Pool Studios, Milwaukee, Wisconsin, United States
2   Cactus Club, Milwaukee, Wisconsin, United States
3  Liliput Records, Milwaukee, Wisconsin, United ...
4   Cactus Club, Milwaukee, Wisconsin, United States

                                Full Address   Latitude  Longitude
0  2496 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
1     3728 N Fratney St, Milwaukee, WI 53212  43.084580 -87.900118
2  2498 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
3    1669 N Farwell Ave, Milwaukee, WI 53202  43.052753 -87.892940
4  2505 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202

[5 rows x 21 columns]

In [151]:
import pandas as pd

# Load your datasets
concerts_ranked = pd.read_csv('data/2024concertsranked.csv')
aggregated_data = pd.read_csv('final_data_aggregated.csv')
venue_bands = pd.read_csv('venue_bands_for_tableau.csv')

# Ensure Start Date is in the same format across datasets
concerts_ranked['Start Date'] = pd.to_datetime(concerts_ranked['Start Date'])
aggregated_data['Start Date'] = pd.to_datetime(aggregated_data['Start Date'])

# Apply the same venue name standardization to concerts_ranked that you applied to aggregated_data
venue_name_mapping = {
    'The Rave/Eagles Club': 'The Rave',
    'Marcus Performing Arts Center': 'Marcus Center for the Performing Arts',
    'Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park-M & I Bank Classic Rock Stage': 'Summerfest'
}

concerts_ranked['Venue'] = concerts_ranked['Venue'].replace(venue_name_mapping)
venue_bands['Venue'] = venue_bands['Venue'].replace(venue_name_mapping)

# Convert slash-delimited bands to comma-delimited in concerts_ranked
concerts_ranked['Bands'] = concerts_ranked['Bands'].str.replace(' / ', ', ')

# Get fields from concerts_ranked (source of truth)
concerts_truth = concerts_ranked[['Start Date', 'Ranking', 'Bands', 'Venue', 'Location', 'Rating', 'Paid', 'Discount']]

# Get fields from aggregated_data
columns_to_exclude = ['Ranking', 'Bands', 'Location', 'Rating', 'Paid', 'Discount']
aggregated_features = aggregated_data.drop(columns=[col for col in columns_to_exclude if col in aggregated_data.columns])

# Merge datasets
combined_data = pd.merge(
    concerts_truth,
    aggregated_features,
    on=['Start Date', 'Venue'],
    how='left'
)

# Add venue_bands tooltip data
final_data = pd.merge(
    combined_data,
    venue_bands[['Venue', 'Venue_Bands_Complete']],
    on='Venue',
    how='left'
)

# Save the final consolidated dataset
final_data.to_csv('final_concert_data_with_tooltips.csv', index=False)

print(f"Final dataset has {final_data.shape[0]} rows and {final_data.shape[1]} columns")
print("First few rows:")
final_data.head()

Missing values in concerts_ranked:
 Ranking          0
Start Date       0
Concert Name    29
Bands            0
Venue            0
Location         0
Rating           0
Paid             0
Discount        18
dtype: int64
Missing values in aggregated_data:
 Start Date                   0
Venue                        0
Location                     0
capacity                     0
Bands                        0
Is Local                     0
Ranking                      0
Rating                       0
Paid                         0
Discount                     0
dist_from_home               0
drive_time                   0
Scrobbles Before Concert     0
Album Name                  24
Release Date                24
Tier                        24
Waited                      28
Venue Location               0
Full Address                 0
Latitude                     0
Longitude                    0
dtype: int64
Missing values in venue_bands:
 Venue                   0
Venue_Bands_Complete    0
dtype: int64
Unique venue names in concerts_ranked after replacement: ['Cactus Club' 'Pool Studios' 'Liliput Records' 'Summerfest' 'Vivarium'
 'Turner Hall Ballroom' 'X-Ray Arcade' 'Riviera Theatre' 'Pabst Theater'
 'The Rave' 'The Riverside Theater'
 'Peck Pavilion, Marcus Center for the Performing Arts'
 "Linneman's Riverwest Inn" '88Nine Radio Milwaukee Studios'
 'Paradigm Coffee' 'Miller High Life Theatre' 'Thalia Hall'
 'Humboldt Park' 'Marcus Center for the Performing Arts'
 'Riverwalk Commons']
Unique venue names in venue_bands after replacement: ['88Nine Radio Milwaukee Studios' 'Cactus Club' 'Humboldt Park'
 'Liliput Records' "Linneman's Riverwest Inn"
 'Marcus Center for the Performing Arts' 'Miller High Life Theatre'
 'Pabst Theater' 'Paradigm Coffee'
 'Peck Pavilion, Marcus Center for the Performing Arts' 'Pool Studios'
 'Riverwalk Commons' 'Riviera Theatre' 'Summerfest' 'Thalia Hall'
 'The Rave' 'The Riverside Theater' 'Turner Hall Ballroom' 'Vivarium'
 'X-Ray Arcade']
Missing values in final_data:
 Start Date                   0
Ranking                      0
Bands                        0
Venue                        0
Location                     0
Rating                       0
Paid                         0
Discount                    18
capacity                     0
Is Local                     0
dist_from_home               0
drive_time                   0
Scrobbles Before Concert     0
Album Name                  24
Release Date                24
Tier                        24
Waited                      28
Venue Location               0
Full Address                 0
Latitude                     0
Longitude                    0
Venue_Bands_Complete         0
dtype: int64
Final dataset has 57 rows and 22 columns
First few rows of the final dataset:
  Start Date  Ranking                                              Bands  \
0 2024-02-08        1                      Willi Carlisle, Golden Shoals
1 2024-01-13        2  Lady Bird, Max Niemann, Jacob Slade, Maximiano...
2 2024-03-31        3  Barely Civil, Magazine Beach, Overhand, Known ...
3 2024-04-20        4                                              Friko
4 2024-08-02        5                           J.E. Sunde, Caley Conway

             Venue                             Location  Rating  Paid  \
0      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1
1     Pool Studios  Milwaukee, Wisconsin, United States     5.0     1
2      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1
3  Liliput Records  Milwaukee, Wisconsin, United States     5.0     0
4      Cactus Club  Milwaukee, Wisconsin, United States     5.0     1

           Discount  capacity  Is Local  ...  Scrobbles Before Concert  \
0               NaN       150         0  ...                        53
1               NaN       250         1  ...                       120
2               NaN       150         1  ...                        78
3  Record Store Day       120         0  ...                        43
4               NaN       150         1  ...                        86

                                Album Name  Release Date    Tier     Waited  \
0                              Critterland    2024-01-26   Top 5  13 day(s)
1                              Soft Spoken    2023-10-13  Top 25  92 day(s)
2                     I'd Say I'm Not Fine    2024-03-22  Top 10   9 day(s)
3  Where we've been, Where we go from here    2024-02-16   Top 5  64 day(s)
4                                      NaN           NaN     NaN        NaN

                                      Venue Location  \
0   Cactus Club, Milwaukee, Wisconsin, United States
1  Pool Studios, Milwaukee, Wisconsin, United States
2   Cactus Club, Milwaukee, Wisconsin, United States
3  Liliput Records, Milwaukee, Wisconsin, United ...
4   Cactus Club, Milwaukee, Wisconsin, United States

                                Full Address   Latitude  Longitude  \
0  2496 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
1     3728 N Fratney St, Milwaukee, WI 53212  43.084580 -87.900118
2  2498 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
3    1669 N Farwell Ave, Milwaukee, WI 53202  43.052753 -87.892940
4  2505 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202

                                Venue_Bands_Complete
0  Willi Carlisle, Golden Shoals, Barely Civil, O...
1  Lady Bird, Max Niemann, Jacob Slade, Maximiano...
2  Willi Carlisle, Golden Shoals, Barely Civil, O...
3                                              Friko
4  Willi Carlisle, Golden Shoals, Barely Civil, O...

[5 rows x 22 columns]

(57, 22)

In [149]:
# Re-importing the necessary libraries
import pandas as pd

# Assuming 'final_data' is already available in the environment
final_data['Start Date'] = pd.to_datetime(final_data['Start Date'])

# Filter for concerts in 2024 and count them
concerts_2024 = final_data[final_data['Start Date'].dt.year == 2024]
concerts_2024_count = concerts_2024.shape[0]
concerts_2024_count

57

In [87]:
 final_data['Discount'].value_counts()

Discount
Street Team         23
Rave Contest         4
Summerfest Promo     3
88nine Member        3
Public Park          2
Record Store Day     1
88nine Call-in       1
Summer of Soul       1
Ushered              1
Name: count, dtype: int64

In [89]:
final_data.isna().sum()

Start Date                   0
Ranking                      0
Bands                        0
Venue                        0
Location                     0
Rating                       0
Paid                         0
Discount                    18
capacity                     0
Is Local                     0
dist_from_home               0
drive_time                   0
Scrobbles Before Concert     0
Album Name                  24
Release Date                24
Tier                        24
Waited                      28
Venue Location               0
Full Address                 0
Latitude                     0
Longitude                    0
Venue_Bands_Complete         0
dtype: int64

In [91]:
# Filter rows where any of these columns have nulls
null_rows = final_data[final_data[['Latitude', 'Longitude', 'Venue_Bands_Complete']].isna().any(axis=1)]

# Display the rows with nulls
null_rows

Empty DataFrame
Columns: [Start Date, Ranking, Bands, Venue, Location, Rating, Paid, Discount, capacity, Is Local, dist_from_home, drive_time, Scrobbles Before Concert, Album Name, Release Date, Tier, Waited, Venue Location, Full Address, Latitude, Longitude, Venue_Bands_Complete]
Index: []

[0 rows x 22 columns]

In [161]:
import pandas as pd

# Load the new dataset (long-term archive data)
concert_archives = pd.read_csv('data/ConcertArchivesExportFeb22-25.csv')

# Load the existing dataset (final data)
final_data = pd.read_csv('final_concert_data_with_tooltips.csv')

# Clean the long-term data before merging
# Rename columns in concert_archives to avoid conflicts
concert_archives = concert_archives.rename(columns={
    'Start Date': 'LongTerm_Start Date',
    'Bands': 'LongTerm_Bands',
    'Venue': 'LongTerm_Venue',
    'Location': 'LongTerm_Location'
})

# Convert 'Start Date' to datetime format (for both datasets)
concert_archives['LongTerm_Start Date'] = pd.to_datetime(concert_archives['LongTerm_Start Date'], format='%m/%d/%Y')
final_data['Start Date'] = pd.to_datetime(final_data['Start Date'], format='%Y-%m-%d')

# Convert LongTerm_Bands from " / " separators to commas
concert_archives['LongTerm_Bands'] = concert_archives['LongTerm_Bands'].str.replace(' / ', ', ')

# Perform the merge with outer join to keep all data from both datasets
combined_data = pd.merge(
    final_data,
    concert_archives,
    left_on=['Start Date', 'Venue'],
    right_on=['LongTerm_Start Date', 'LongTerm_Venue'],
    how='outer'
)

# Save the combined dataset (with both original and long-term columns)
combined_data.to_csv('combined_concert_data_with_tooltip.csv', index=False)

# Optionally, inspect the first few rows of the combined dataset
combined_data.head()
combined_data.shape

(226, 28)

In [107]:
import pandas as pd

# Load the original dataset
original_data = pd.read_csv('final_concert_data_with_tooltips.csv')

# Load the merged dataset
merged_data = pd.read_csv('final_concert_data_with_tooltips.csv')

# Identify concerts in original_data not in merged_data
missing_concerts = original_data[~original_data['Start Date'].isin(merged_data['Start Date'])]

print("Missing concerts:")
print(missing_concerts)

Missing concerts:
Empty DataFrame
Columns: [Start Date, Ranking, Bands, Venue, Location, Rating, Paid, Discount, capacity, Is Local, dist_from_home, drive_time, Scrobbles Before Concert, Album Name, Release Date, Tier, Waited, Venue Location, Full Address, Latitude, Longitude, Venue_Bands_Complete, LongTerm_Start Date, LongTerm_Bands, LongTerm_Venue, LongTerm_Location]
Index: []

[0 rows x 26 columns]

In [109]:
import pandas as pd

# Load the datasets again for comparison
original_data = pd.read_csv('final_concert_data_with_tooltips.csv')
concert_archives = pd.read_csv('data/ConcertArchives_cleaned.csv')

# Check for duplicate concerts in both datasets
original_duplicates = original_data[original_data.duplicated(subset=['Start Date', 'Venue'], keep=False)]
cleaned_duplicates = concert_archives[concert_archives.duplicated(subset=['LongTerm_Start Date', 'LongTerm_Venue'], keep=False)]

# Display duplicates
print("Duplicates in original data:")
print(original_duplicates)

print("Duplicates in cleaned data:")
print(cleaned_duplicates)

Duplicates in original data:
    Start Date  Ranking Bands Venue Location  Rating  Paid Discount  capacity  \
57         NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
58         NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
59         NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
60         NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
61         NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
..         ...      ...   ...   ...      ...     ...   ...      ...       ...
221        NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
222        NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
223        NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
224        NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN
225        NaN      NaN   NaN   NaN      NaN     NaN   NaN      NaN       NaN

     Is Local  ...  Waited  Venue Location  Full Address Latitude Longitude  \
57        NaN  ...     NaN             NaN           NaN      NaN       NaN
58        NaN  ...     NaN             NaN           NaN      NaN       NaN
59        NaN  ...     NaN             NaN           NaN      NaN       NaN
60        NaN  ...     NaN             NaN           NaN      NaN       NaN
61        NaN  ...     NaN             NaN           NaN      NaN       NaN
..        ...  ...     ...             ...           ...      ...       ...
221       NaN  ...     NaN             NaN           NaN      NaN       NaN
222       NaN  ...     NaN             NaN           NaN      NaN       NaN
223       NaN  ...     NaN             NaN           NaN      NaN       NaN
224       NaN  ...     NaN             NaN           NaN      NaN       NaN
225       NaN  ...     NaN             NaN           NaN      NaN       NaN

    Venue_Bands_Complete LongTerm_Start Date  \
57                   NaN          2025-02-22
58                   NaN          2025-01-29
59                   NaN          2025-01-24
60                   NaN          2025-01-23
61                   NaN          2024-09-22
..                   ...                 ...
221                  NaN          2011-11-18
222                  NaN          2011-07-26
223                  NaN          2010-07-11
224                  NaN          2010-03-06
225                  NaN          2010-02-19

                                     LongTerm_Bands  \
57   Barely Civil, Wave Chapelle, Caley Conway, 2hi
58                      Almost Monday, Adrian Lyles
59                      Beach Bunny, Delaney Bailey
60                  Orillia, Poor Ridley, Maximiano
61                  A.A. Williams, Jorge Vallentine
..                                              ...
221                              The Avett Brothers
222                  Blitzen Trapper, Ages and Ages
223            The Avett Brothers, Elephant Revival
224              The Low Anthem, The Avett Brothers
225                                    Diane Schuur

                        LongTerm_Venue                    LongTerm_Location
57                       Amorphic Beer  Milwaukee, Wisconsin, United States
58                            Vivarium  Milwaukee, Wisconsin, United States
59                Turner Hall Ballroom  Milwaukee, Wisconsin, United States
60                         Sugar Maple  Milwaukee, Wisconsin, United States
61                        X-Ray Arcade  Milwaukee, Wisconsin, United States
..                                 ...                                  ...
221              The Riverside Theater  Milwaukee, Wisconsin, United States
222                           Slowdown       Omaha, Nebraska, United States
223   Lake Superior Big Top Chautauqua                         Bayfield, WI
224              The Riverside Theater  Milwaukee, Wisconsin, United States
225  Fox Cities Performing Arts Center   Appleton, Wisconsin, United States

[169 rows x 26 columns]
Duplicates in cleaned data:
Empty DataFrame
Columns: [LongTerm_Start Date, LongTerm_Bands, LongTerm_Venue, LongTerm_Location]
Index: []

In [111]:
# Look for concerts in the original dataset but missing in the merged dataset
missing_in_merged = original_data[~original_data[['Start Date', 'Venue']].apply(tuple, axis=1).isin(combined_data[['Start Date', 'Venue']].apply(tuple, axis=1))]

# Check how many concerts are missing and display the details
print(f"Missing concerts in merged data: {missing_in_merged.shape[0]}")
print(missing_in_merged[['Start Date', 'Venue', 'Bands']])

Missing concerts in merged data: 0
Empty DataFrame
Columns: [Start Date, Venue, Bands]
Index: []

In [113]:
# Check for partial matches between the original and merged datasets
unmatched_venues = original_data[~original_data['Venue'].isin(concert_archives['LongTerm_Venue'])]
print(f"Unmatched venues in original data: {unmatched_venues[['Start Date', 'Venue']].head()}")

Unmatched venues in original data:    Start Date Venue
57        NaN   NaN
58        NaN   NaN
59        NaN   NaN
60        NaN   NaN
61        NaN   NaN

In [115]:
last_concert = original_data[original_data['Start Date'] == '2024-12-31']
print(last_concert)

Empty DataFrame
Columns: [Start Date, Ranking, Bands, Venue, Location, Rating, Paid, Discount, capacity, Is Local, dist_from_home, drive_time, Scrobbles Before Concert, Album Name, Release Date, Tier, Waited, Venue Location, Full Address, Latitude, Longitude, Venue_Bands_Complete, LongTerm_Start Date, LongTerm_Bands, LongTerm_Venue, LongTerm_Location]
Index: []

[0 rows x 26 columns]

In [117]:
print(f"Concerts in original data: {original_data.shape[0]}")
print(f"Concerts in final merged data: {combined_data.shape[0]}")

Concerts in original data: 226
Concerts in final merged data: 226

In [119]:
import pandas as pd

# Load the manually updated dataset
concerts_ranked = pd.read_csv('data/2024concertsranked.csv')

# Check for missing values in key columns (Start Date, Venue, Bands)
print("Missing values in key columns:")
print(concerts_ranked[['Start Date', 'Venue', 'Bands']].isna().sum())

# Check unique values in 'Venue' to see if any names are inconsistent
print("\nUnique venue names:")
print(sorted(concerts_ranked['Venue'].unique()))

# Check the overall shape of the dataset to ensure it contains the expected number of concerts
print(f"\nNumber of concerts in '2024concertsranked.csv': {concerts_ranked.shape[0]}")

Missing values in key columns:
Start Date    0
Venue         0
Bands         0
dtype: int64

Unique venue names:
['88Nine Radio Milwaukee Studios', 'Cactus Club', 'Henry Maier Festival Park', 'Humboldt Park', 'Liliput Records', "Linneman's Riverwest Inn", 'Marcus Center for the Performing Arts', 'Miller High Life Theatre', 'Pabst Theater', 'Paradigm Coffee', 'Peck Pavilion, Marcus Center for the Performing Arts', 'Pool Studios', 'Riverwalk Commons', 'Riviera Theatre', 'Summerfest', 'Summerfest Grounds at Henry Maier Festival Park', 'Summerfest Grounds at Henry Maier Festival Park-M & I Bank Classic Rock Stage', 'Thalia Hall', 'The Rave', 'The Rave/Eagles Club', 'The Riverside Theater', 'Turner Hall Ballroom', 'Vivarium', 'X-Ray Arcade']

Number of concerts in '2024concertsranked.csv': 57

In [121]:
# Define the mapping for venue name standardization
venue_name_mapping = {
    'The Rave/Eagles Club': 'The Rave',
    'Marcus Performing Arts Center': 'Marcus Center for the Performing Arts',
    'Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park': 'Summerfest',
    'Summerfest Grounds at Henry Maier Festival Park-M & I Bank Classic Rock Stage': 'Summerfest'
}

# Apply the venue name standardization
concerts_ranked['Venue'] = concerts_ranked['Venue'].replace(venue_name_mapping)

# Check again for unique venue names to see the result
print("\nUpdated unique venue names after standardization:")
print(sorted(concerts_ranked['Venue'].unique()))

Updated unique venue names after standardization:
['88Nine Radio Milwaukee Studios', 'Cactus Club', 'Humboldt Park', 'Liliput Records', "Linneman's Riverwest Inn", 'Marcus Center for the Performing Arts', 'Miller High Life Theatre', 'Pabst Theater', 'Paradigm Coffee', 'Peck Pavilion, Marcus Center for the Performing Arts', 'Pool Studios', 'Riverwalk Commons', 'Riviera Theatre', 'Summerfest', 'Thalia Hall', 'The Rave', 'The Riverside Theater', 'Turner Hall Ballroom', 'Vivarium', 'X-Ray Arcade']

In [123]:
# Load the aggregated data
aggregated_data = pd.read_csv('final_data_aggregated.csv')

# Ensure Start Date is in the same format in both datasets
concerts_ranked['Start Date'] = pd.to_datetime(concerts_ranked['Start Date'])
aggregated_data['Start Date'] = pd.to_datetime(aggregated_data['Start Date'])

# Merge the two datasets on 'Start Date' and 'Venue'
combined_data = pd.merge(
    concerts_ranked[['Start Date', 'Ranking', 'Bands', 'Venue', 'Location', 'Rating', 'Paid', 'Discount']],  # Source of truth fields
    aggregated_data,  # Data with the extra information
    on=['Start Date', 'Venue'],
    how='left'  # Keep all concerts from concerts_ranked and add matched data from aggregated_data
)

# Check for any missing values after the merge
missing_data = combined_data[combined_data['capacity'].isna()]
if not missing_data.empty:
    print(f"Warning: {len(missing_data)} concerts didn't match with aggregated data:")
    print(missing_data[['Start Date', 'Venue', 'Bands']])

# Save the combined dataset
combined_data.to_csv('combined_concert_data_final.csv', index=False)

# Preview the combined data
print(f"Combined data has {combined_data.shape[0]} rows and {combined_data.shape[1]} columns")
print("First few rows:")
print(combined_data.head())

Combined data has 57 rows and 27 columns
First few rows:
  Start Date  Ranking_x                                            Bands_x  \
0 2024-02-08          1                     Willi Carlisle / Golden Shoals
1 2024-01-13          2  Lady Bird / Max Niemann / Jacob Slade / Maximi...
2 2024-03-31          3  Barely Civil / Magazine Beach / Overhand / Kno...
3 2024-04-20          4                                              Friko
4 2024-08-02          5                          J.E. Sunde / Caley Conway

             Venue                           Location_x  Rating_x  Paid_x  \
0      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1
1     Pool Studios  Milwaukee, Wisconsin, United States       5.0       1
2      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1
3  Liliput Records  Milwaukee, Wisconsin, United States       5.0       0
4      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1

         Discount_x                           Location_y  capacity  ...  \
0               NaN  Milwaukee, Wisconsin, United States       150  ...
1               NaN  Milwaukee, Wisconsin, United States       250  ...
2               NaN  Milwaukee, Wisconsin, United States       150  ...
3  Record Store Day  Milwaukee, Wisconsin, United States       120  ...
4               NaN  Milwaukee, Wisconsin, United States       150  ...

  drive_time  Scrobbles Before Concert  \
0         15                        53
1         12                       120
2         15                        78
3         16                        43
4         15                        86

                                Album Name  Release Date    Tier     Waited  \
0                              Critterland    2024-01-26   Top 5  13 day(s)
1                              Soft Spoken    2023-10-13  Top 25  92 day(s)
2                     I'd Say I'm Not Fine    2024-03-22  Top 10   9 day(s)
3  Where we've been, Where we go from here    2024-02-16   Top 5  64 day(s)
4                                      NaN           NaN     NaN        NaN

                                      Venue Location  \
0   Cactus Club, Milwaukee, Wisconsin, United States
1  Pool Studios, Milwaukee, Wisconsin, United States
2   Cactus Club, Milwaukee, Wisconsin, United States
3  Liliput Records, Milwaukee, Wisconsin, United ...
4   Cactus Club, Milwaukee, Wisconsin, United States

                                Full Address   Latitude  Longitude
0  2496 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
1     3728 N Fratney St, Milwaukee, WI 53212  43.084580 -87.900118
2  2498 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
3    1669 N Farwell Ave, Milwaukee, WI 53202  43.052753 -87.892940
4  2505 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202

[5 rows x 27 columns]

In [125]:
# Check for missing concerts in the final dataset compared to the concert archives
missing_concerts = concert_archives[~concert_archives['LongTerm_Start Date'].isin(final_data['Start Date'])]
print(missing_concerts)

    LongTerm_Start Date                                  LongTerm_Bands  \
0            2025-02-22  Barely Civil, Wave Chapelle, Caley Conway, 2hi
1            2025-01-29                     Almost Monday, Adrian Lyles
2            2025-01-24                     Beach Bunny, Delaney Bailey
3            2025-01-23                 Orillia, Poor Ridley, Maximiano
14           2024-09-22                 A.A. Williams, Jorge Vallentine
..                  ...                                             ...
216          2011-11-18                              The Avett Brothers
217          2011-07-26                  Blitzen Trapper, Ages and Ages
218          2010-07-11            The Avett Brothers, Elephant Revival
219          2010-03-06              The Low Anthem, The Avett Brothers
220          2010-02-19                                    Diane Schuur

                        LongTerm_Venue                    LongTerm_Location
0                        Amorphic Beer  Milwaukee, Wisconsin, United States
1                             Vivarium  Milwaukee, Wisconsin, United States
2                 Turner Hall Ballroom  Milwaukee, Wisconsin, United States
3                          Sugar Maple  Milwaukee, Wisconsin, United States
14                        X-Ray Arcade  Milwaukee, Wisconsin, United States
..                                 ...                                  ...
216              The Riverside Theater  Milwaukee, Wisconsin, United States
217                           Slowdown       Omaha, Nebraska, United States
218   Lake Superior Big Top Chautauqua                         Bayfield, WI
219              The Riverside Theater  Milwaukee, Wisconsin, United States
220  Fox Cities Performing Arts Center   Appleton, Wisconsin, United States

[164 rows x 4 columns]

In [127]:
import pandas as pd

# Load the datasets
combined_data = pd.read_csv('combined_concert_data_final.csv')
final_data = pd.read_csv('final_concert_data_with_tooltips.csv')

# Convert 'Start Date' to datetime to filter by year
combined_data['Start Date'] = pd.to_datetime(combined_data['Start Date'])
final_data['Start Date'] = pd.to_datetime(final_data['Start Date'])

# Filter only 2024 concerts
combined_data_2024 = combined_data[combined_data['Start Date'].dt.year == 2024]
final_data_2024 = final_data[final_data['Start Date'].dt.year == 2024]

# Find concerts in 2024 that are in combined_data but not in final_data
missing_in_final = combined_data_2024[~combined_data_2024['Start Date'].isin(final_data_2024['Start Date'])]

# Find concerts in 2024 that are in final_data but not in combined_data
missing_in_combined = final_data_2024[~final_data_2024['Start Date'].isin(combined_data_2024['Start Date'])]

# Output the results
print("Concerts in combined_data but missing in final_data:")
print(missing_in_final)

print("\nConcerts in final_data but missing in combined_data:")
print(missing_in_combined)

Concerts in combined_data but missing in final_data:
Empty DataFrame
Columns: [Start Date, Ranking_x, Bands_x, Venue, Location_x, Rating_x, Paid_x, Discount_x, Location_y, capacity, Bands_y, Is Local, Ranking_y, Rating_y, Paid_y, Discount_y, dist_from_home, drive_time, Scrobbles Before Concert, Album Name, Release Date, Tier, Waited, Venue Location, Full Address, Latitude, Longitude]
Index: []

[0 rows x 27 columns]

Concerts in final_data but missing in combined_data:
Empty DataFrame
Columns: [Start Date, Ranking, Bands, Venue, Location, Rating, Paid, Discount, capacity, Is Local, dist_from_home, drive_time, Scrobbles Before Concert, Album Name, Release Date, Tier, Waited, Venue Location, Full Address, Latitude, Longitude, Venue_Bands_Complete, LongTerm_Start Date, LongTerm_Bands, LongTerm_Venue, LongTerm_Location]
Index: []

[0 rows x 26 columns]

In [129]:
# View the first few rows of both datasets for 2024
print("First few rows of combined_data_2024:")
print(combined_data_2024.head())

print("\nFirst few rows of final_data_2024:")
print(final_data_2024.head())

First few rows of combined_data_2024:
  Start Date  Ranking_x                                            Bands_x  \
0 2024-02-08          1                     Willi Carlisle / Golden Shoals
1 2024-01-13          2  Lady Bird / Max Niemann / Jacob Slade / Maximi...
2 2024-03-31          3  Barely Civil / Magazine Beach / Overhand / Kno...
3 2024-04-20          4                                              Friko
4 2024-08-02          5                          J.E. Sunde / Caley Conway

             Venue                           Location_x  Rating_x  Paid_x  \
0      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1
1     Pool Studios  Milwaukee, Wisconsin, United States       5.0       1
2      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1
3  Liliput Records  Milwaukee, Wisconsin, United States       5.0       0
4      Cactus Club  Milwaukee, Wisconsin, United States       5.0       1

         Discount_x                           Location_y  capacity  ...  \
0               NaN  Milwaukee, Wisconsin, United States       150  ...
1               NaN  Milwaukee, Wisconsin, United States       250  ...
2               NaN  Milwaukee, Wisconsin, United States       150  ...
3  Record Store Day  Milwaukee, Wisconsin, United States       120  ...
4               NaN  Milwaukee, Wisconsin, United States       150  ...

  drive_time  Scrobbles Before Concert  \
0         15                        53
1         12                       120
2         15                        78
3         16                        43
4         15                        86

                                Album Name  Release Date    Tier     Waited  \
0                              Critterland    2024-01-26   Top 5  13 day(s)
1                              Soft Spoken    2023-10-13  Top 25  92 day(s)
2                     I'd Say I'm Not Fine    2024-03-22  Top 10   9 day(s)
3  Where we've been, Where we go from here    2024-02-16   Top 5  64 day(s)
4                                      NaN           NaN     NaN        NaN

                                      Venue Location  \
0   Cactus Club, Milwaukee, Wisconsin, United States
1  Pool Studios, Milwaukee, Wisconsin, United States
2   Cactus Club, Milwaukee, Wisconsin, United States
3  Liliput Records, Milwaukee, Wisconsin, United ...
4   Cactus Club, Milwaukee, Wisconsin, United States

                                Full Address   Latitude  Longitude
0  2496 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
1     3728 N Fratney St, Milwaukee, WI 53212  43.084580 -87.900118
2  2498 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
3    1669 N Farwell Ave, Milwaukee, WI 53202  43.052753 -87.892940
4  2505 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202

[5 rows x 27 columns]

First few rows of final_data_2024:
  Start Date  Ranking                                              Bands  \
0 2024-02-08      1.0                      Willi Carlisle, Golden Shoals
1 2024-01-13      2.0  Lady Bird, Max Niemann, Jacob Slade, Maximiano...
2 2024-03-31      3.0  Barely Civil, Magazine Beach, Overhand, Known ...
3 2024-04-20      4.0                                              Friko
4 2024-08-02      5.0                           J.E. Sunde, Caley Conway

             Venue                             Location  Rating  Paid  \
0      Cactus Club  Milwaukee, Wisconsin, United States     5.0   1.0
1     Pool Studios  Milwaukee, Wisconsin, United States     5.0   1.0
2      Cactus Club  Milwaukee, Wisconsin, United States     5.0   1.0
3  Liliput Records  Milwaukee, Wisconsin, United States     5.0   0.0
4      Cactus Club  Milwaukee, Wisconsin, United States     5.0   1.0

           Discount  capacity  Is Local  ...     Waited  \
0               NaN     150.0       0.0  ...  13 day(s)
1               NaN     250.0       1.0  ...  92 day(s)
2               NaN     150.0       1.0  ...   9 day(s)
3  Record Store Day     120.0       0.0  ...  64 day(s)
4               NaN     150.0       1.0  ...        NaN

                                      Venue Location  \
0   Cactus Club, Milwaukee, Wisconsin, United States
1  Pool Studios, Milwaukee, Wisconsin, United States
2   Cactus Club, Milwaukee, Wisconsin, United States
3  Liliput Records, Milwaukee, Wisconsin, United ...
4   Cactus Club, Milwaukee, Wisconsin, United States

                                Full Address   Latitude  Longitude  \
0  2496 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
1     3728 N Fratney St, Milwaukee, WI 53212  43.084580 -87.900118
2  2498 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202
3    1669 N Farwell Ave, Milwaukee, WI 53202  43.052753 -87.892940
4  2505 S Wentworth Ave, Milwaukee, WI 53207  42.999030 -87.890202

                                Venue_Bands_Complete LongTerm_Start Date  \
0  Willi Carlisle, Golden Shoals, Barely Civil, O...          2024-02-08
1  Lady Bird, Max Niemann, Jacob Slade, Maximiano...          2024-01-13
2  Willi Carlisle, Golden Shoals, Barely Civil, O...          2024-03-31
3                                              Friko          2024-04-20
4  Willi Carlisle, Golden Shoals, Barely Civil, O...          2024-08-02

                                      LongTerm_Bands   LongTerm_Venue  \
0                      Willi Carlisle, Golden Shoals      Cactus Club
1  Lady Bird, Max Niemann, Jacob Slade, Maximiano...     Pool Studios
2  Barely Civil, Magazine Beach, Overhand, Known ...      Cactus Club
3                                              Friko  Liliput Records
4                           J.E. Sunde, Caley Conway      Cactus Club

                     LongTerm_Location
0  Milwaukee, Wisconsin, United States
1  Milwaukee, Wisconsin, United States
2  Milwaukee, Wisconsin, United States
3  Milwaukee, Wisconsin, United States
4  Milwaukee, Wisconsin, United States

[5 rows x 26 columns]

In [133]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('final_concert_data_with_tooltips.csv')

# Find the row containing Taylor Bennett in the Venue Bands Complete column
# Update the 'LongTerm Start Date' for that row
df.loc[df['Venue Bands Complete'].str.contains('Taylor Bennett', na=False), 'LongTerm Start Date'] = '06/21/2024'

# Save the updated DataFrame back to CSV
df.to_csv('final_concert_data_with_tooltips.csv', index=False)

print("Date updated successfully!")

KeyError: 'Venue Bands Complete'

In [135]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('final_concert_data_with_tooltips.csv')

# Print the column names to confirm the exact name
print(df.columns)

Index(['Start Date', 'Ranking', 'Bands', 'Venue', 'Location', 'Rating', 'Paid',
       'Discount', 'capacity', 'Is Local', 'dist_from_home', 'drive_time',
       'Scrobbles Before Concert', 'Album Name', 'Release Date', 'Tier',
       'Waited', 'Venue Location', 'Full Address', 'Latitude', 'Longitude',
       'Venue_Bands_Complete', 'LongTerm_Start Date', 'LongTerm_Bands',
       'LongTerm_Venue', 'LongTerm_Location'],
      dtype='object')

In [145]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('final_concert_data_with_tooltips.csv')

# Update the LongTerm Start Date for Taylor Bennett in Venue_Bands_Complete
df.loc[df['Venue_Bands_Complete'].str.contains('Taylor Bennett', na=False), 'LongTerm_Start Date'] = '06/21/2024'

# Print the row where Taylor Bennett is mentioned to check if the date was updated
print(df[df['Venue_Bands_Complete'].str.contains('Taylor Bennett', na=False)])

# Save the updated dataframe back to a CSV
df.to_csv('final_concert_data_with_tooltips_updated.csv', index=False)

df

    Start Date  Ranking                                             Bands  \
5   2024-07-05      6.0                                     Local Natives
19  2024-06-27     20.0            Brigitte Calls Me Baby, grouptherapy.
33  2024-06-21     34.0                  Charlotte Cardin, Taylor Bennett
34  2024-07-04     35.0  Wave Chapelle, Ellie Jackson, Reyna, Say She She
36  2024-07-06     37.0                                         Amy Grant

         Venue                             Location  Rating  Paid  \
5   Summerfest  Milwaukee, Wisconsin, United States     5.0   1.0
19  Summerfest  Milwaukee, Wisconsin, United States     4.5   0.0
33  Summerfest  Milwaukee, Wisconsin, United States     4.0   0.0
34  Summerfest  Milwaukee, Wisconsin, United States     4.0   0.0
36  Summerfest  Milwaukee, Wisconsin, United States     4.0   0.0

            Discount  capacity  Is Local  ...      Waited  \
5                NaN   10000.0       0.0  ...  364 day(s)
19       Street Team   10000.0       0.0  ...         NaN
33  Summerfest Promo   10000.0       0.0  ...  301 day(s)
34  Summerfest Promo   10000.0       1.0  ...  426 day(s)
36  Summerfest Promo   10000.0       0.0  ...         NaN

                                       Venue Location  \
5     Summerfest, Milwaukee, Wisconsin, United States
19    Summerfest, Milwaukee, Wisconsin, United States
33  Summerfest Grounds at Henry Maier Festival Par...
34  Summerfest Grounds at Henry Maier Festival Par...
36    Summerfest, Milwaukee, Wisconsin, United States

                                         Full Address   Latitude  Longitude  \
5                200 N Harbor Dr, Milwaukee, WI 53202  43.031061 -87.899516
19  200 North Harbor Drive, Milwaukee, Wisconsin 5...  43.031061 -87.899516
33               200 N Harbor Dr, Milwaukee, WI 53202  43.031061 -87.899516
34               200 N Harbor Dr, Milwaukee, WI 53202  43.031061 -87.899516
36               200 N Harbor Dr, Milwaukee, WI 53202  43.031061 -87.899516

                                 Venue_Bands_Complete LongTerm_Start Date  \
5   Charlotte Cardin, Taylor Bennett, Brigitte Cal...          06/21/2024
19  Charlotte Cardin, Taylor Bennett, Brigitte Cal...          06/21/2024
33  Charlotte Cardin, Taylor Bennett, Brigitte Cal...          06/21/2024
34  Charlotte Cardin, Taylor Bennett, Brigitte Cal...          06/21/2024
36  Charlotte Cardin, Taylor Bennett, Brigitte Cal...          06/21/2024

                                       LongTerm_Bands LongTerm_Venue  \
5                                       Local Natives     Summerfest
19                                                NaN            NaN
33                                                NaN            NaN
34                                                NaN            NaN
36  Chase Rice, Amy Grant, Extreme, BoDeans, Siste...     Summerfest

                      LongTerm_Location
5   Milwaukee, Wisconsin, United States
19                                  NaN
33                                  NaN
34                                  NaN
36  Milwaukee, Wisconsin, United States

[5 rows x 26 columns]

,Start Date,Ranking,Bands,Venue,Location,Rating,Paid,Discount,capacity,Is Local,...,Waited,Venue Location,Full Address,Latitude,Longitude,Venue_Bands_Complete,LongTerm_Start Date,LongTerm_Bands,LongTerm_Venue,LongTerm_Location
0,2024-02-08,1.0,"Willi Carlisle, Golden Shoals",Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1.0,NaN,150.0,0.0,...,13 day(s),"Cactus Club, Milwaukee, Wisconsin, United States","2496 S Wentworth Ave, Milwaukee, WI 53207",42.999030,-87.890202,"Willi Carlisle, Golden Shoals, Barely Civil, O...",2024-02-08,"Willi Carlisle, Golden Shoals",Cactus Club,"Milwaukee, Wisconsin, United States"
1,2024-01-13,2.0,"Lady Bird, Max Niemann, Jacob Slade, Maximiano...",Pool Studios,"Milwaukee, Wisconsin, United States",5.0,1.0,NaN,250.0,1.0,...,92 day(s),"Pool Studios, Milwaukee, Wisconsin, United States","3728 N Fratney St, Milwaukee, WI 53212",43.084580,-87.900118,"Lady Bird, Max Niemann, Jacob Slade, Maximiano...",2024-01-13,"Lady Bird, Max Niemann, Jacob Slade, Maximiano...",Pool Studios,"Milwaukee, Wisconsin, United States"
2,2024-03-31,3.0,"Barely Civil, Magazine Beach, Overhand, Known ...",Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1.0,NaN,150.0,1.0,...,9 day(s),"Cactus Club, Milwaukee, Wisconsin, United States","2498 S Wentworth Ave, Milwaukee, WI 53207",42.999030,-87.890202,"Willi Carlisle, Golden Shoals, Barely Civil, O...",2024-03-31,"Barely Civil, Magazine Beach, Overhand, Known ...",Cactus Club,"Milwaukee, Wisconsin, United States"
3,2024-04-20,4.0,Friko,Liliput Records,"Milwaukee, Wisconsin, United States",5.0,0.0,Record Store Day,120.0,0.0,...,64 day(s),"Liliput Records, Milwaukee, Wisconsin, United ...","1669 N Farwell Ave, Milwaukee, WI 53202",43.052753,-87.892940,Friko,2024-04-20,Friko,Liliput Records,"Milwaukee, Wisconsin, United States"
4,2024-08-02,5.0,"J.E. Sunde, Caley Conway",Cactus Club,"Milwaukee, Wisconsin, United States",5.0,1.0,NaN,150.0,1.0,...,NaN,"Cactus Club, Milwaukee, Wisconsin, United States","2505 S Wentworth Ave, Milwaukee, WI 53207",42.999030,-87.890202,"Willi Carlisle, Golden Shoals, Barely Civil, O...",2024-08-02,"J.E. Sunde, Caley Conway",Cactus Club,"Milwaukee, Wisconsin, United States"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2011-11-18,The Avett Brothers,The Riverside Theater,"Milwaukee, Wisconsin, United States"
222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2011-07-26,"Blitzen Trapper, Ages and Ages",Slowdown,"Omaha, Nebraska, United States"
223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2010-07-11,"The Avett Brothers, Elephant Revival",Lake Superior Big Top Chautauqua,"Bayfield, WI"
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2010-03-06,"The Low Anthem, The Avett Brothers",The Riverside Theater,"Milwaukee, Wisconsin, United States"
225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2010-02-19,Diane Schuur,Fox Cities Performing Arts Center,"Appleton, Wisconsin, United States"